#! /bin/sh
# Copyright (C) 2009-2012  CEA/DEN, EDF R&D
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#

ORIG_DIR=`pwd`
run() {
    local logfile=$ORIG_DIR/build_configure.log
    printf "%-50s" "$1 ... "
    eval $1 > $logfile 2>&1
    if test $? != 0 ; then
        echo "[FAILED]"
        echo "see file build_configure.log ..."
        exit 1
    fi
    echo "[  OK  ]"
}

run "libtoolize --force --copy --automake"
run "aclocal -I m4"
run "autoheader -I m4"
run "autoconf"
run "automake --add-missing --copy"

